SET HEA OFF;
SET LINESHOW OFF;
SET TIMING OFF;
SELECT 
  TOP 1 
  CASE 
    WHEN TIMESTAMPADD(SQL_TSI_DAY, 90, NOW()) > EXPIRED_DATE 
  THEN 1 ELSE 0 
  END AS EXPIRE_RISK 
FROM V$LICENSE 
ORDER BY EXPIRED_DATE ASC;
